// please refer to the remarks I've made...


/*
	iScreen string defines

	English Version:
	#define <SOMEWORD>1	"..."

	Local Version:
	#define <SOMEWORD>2	"..."
*/

// iScreen tutorial texts...

#define BT00_TEXT1	"Save game..."
#define BT00_TEXT2	"Сохранить игру..."
#define BT00_TEXT3	"Spiel speichern..."

#define BT01_TEXT1	"Up to world..."
#define BT01_TEXT2	"Наверх..."
#define BT01_TEXT3	"Hinauf in die Welt..."

#define BT02_TEXT1	"Let's talk..."
#define BT02_TEXT2	"Продолжить беседу..."
#define BT02_TEXT3	"Laс uns reden..."

#define BT03_TEXT1	"Inquire..."
#define BT03_TEXT2	"Спросить..."
#define BT03_TEXT3	"Frage..."

#define BT04_TEXT1	"Trade..."
#define BT04_TEXT2	"Торговля..."
#define BT04_TEXT3	"Handeln..."

#define BT05_TEXT1	"Speak..."
#define BT05_TEXT2	"Сказать..."
#define BT05_TEXT3	"Sprechen..."		// does that belong to 'Trade'? Does it mean: 'offer'?
						// Than please use: 'Bieten...'

#define BT06_TEXT1	"Gears here!"
#define BT06_TEXT2	"Здесь амуниция!"
#define BT06_TEXT3	"Hier gibt's AusrБstung!"

#define BT07_TEXT1	"Mechoses here!"
#define BT07_TEXT2	"Здесь мехосы!"
#define BT07_TEXT3	"Hier gibt's Mechos!"

#define BT08_TEXT1	"Wares here!"
#define BT08_TEXT2	"Здесь товар!"
#define BT08_TEXT3	"Hier gibt's Waren!"

#define BT09_TEXT1	"Back to counselor..."
#define BT09_TEXT2	"Назад к советнику..."
#define BT09_TEXT3	"ZurБck zum Konsular..."

#define BT10_TEXT1	"Previous item..."
#define BT10_TEXT2	"Предыдущий предмет..."
#define BT10_TEXT3	"Vorheriger Gegenstand..."		// too long? Use: 'ZurБck...'

#define BT11_TEXT1	"List of items..."
#define BT11_TEXT2	"Список предметов..."
#define BT11_TEXT3	"Liste der GegenstДnde..."		// too long: Use: 'Liste...'

#define BT12_TEXT1	"Next item..."
#define BT12_TEXT2	"Следующий предмет..."
#define BT12_TEXT3	"NДchster Gegenstand..."		// too long? Use: 'NДchster...'

#define BT13_TEXT1	"Cancel the deal..."
#define BT13_TEXT2	"Прервать сделку..."
#define BT13_TEXT3	"Deal abbrechen..."

#define BT14_TEXT1	"Autoloading..."
#define BT14_TEXT2	"Переместить содержимое мехоса..."
#define BT14_TEXT3	"Auto-Laden..."

#define BT15_TEXT1	"Buy the mechos!"
#define BT15_TEXT2	"Купить мехос!"
#define BT15_TEXT3	"Diesen Mecho kaufen!"

#define AVI_TEXT1	"Take this!"
#define AVI_TEXT2	"Взять!"
#define AVI_TEXT3	"Das will ich!"
